In [1]:
import numpy as np

In [2]:
studentdata = np.loadtxt('data.txt', skiprows=1, delimiter=',',dtype = int)
studentdata

array([[ 1, 36, 18, 57],
       [ 2, 22, 23, 45],
       [ 3, 43, 51, 37],
       [ 4, 41, 40, 60],
       [ 5, 13, 18, 37]])

In [3]:
#unpack = False for row wise extraction and True for column extraction
stud1, stud2, stud3, stud4, stud5 = np.loadtxt('data.txt',skiprows=1,
delimiter=',', dtype = int)


In [5]:
stud1

array([ 1, 36, 18, 57])

In [6]:
stud2

array([ 2, 22, 23, 45])

In [7]:
stud3

array([ 3, 43, 51, 37])

In [8]:
stud4

array([ 4, 41, 40, 60])

In [9]:
stud5

array([ 5, 13, 18, 37])

In [11]:
sno,mks1,mks2,mks3 = np.loadtxt('data.txt',skiprows=1,
delimiter=',', unpack=True,dtype = int)

In [12]:
sno

array([1, 2, 3, 4, 5])

In [13]:
mks1

array([36, 22, 43, 41, 13])

In [14]:
mks2

array([18, 23, 51, 40, 18])

In [15]:
mks3

array([57, 45, 37, 60, 37])

In [16]:
#Using NumPy.genfromtxt()
dataarray = np.genfromtxt('data1.txt',skip_header=1,delimiter = ',')
dataarray

array([[ 1., 36., 18., 57.],
       [ 2., nan, 23., 45.],
       [ 3., 43., 51., nan],
       [ 4., 41., 40., 60.],
       [ 5., 13., 18., 27.]])

In [18]:
dataarray = np.genfromtxt('data1.txt',skip_header=1,delimiter=',', filling_values=-999,
dtype = int)
dataarray

array([[   1,   36,   18,   57],
       [   2, -999,   23,   45],
       [   3,   43,   51, -999],
       [   4,   41,   40,   60],
       [   5,   13,   18,   27]])